
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Feb 27 12:17:25 EST 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int _16 = 17;
  public static final int _15 = 16;
  public static final int _9 = 10;
  public static final int _14 = 15;
  public static final int _8 = 9;
  public static final int _13 = 14;
  public static final int _7 = 8;
  public static final int _12 = 13;
  public static final int _6 = 7;
  public static final int _11 = 12;
  public static final int _5 = 6;
  public static final int _10 = 11;
  public static final int _4 = 5;
  public static final int _3 = 4;
  public static final int _2 = 3;
  public static final int _1 = 2;
  public static final int IF = 19;
  public static final int ID = 18;
  public static final int NUMBER = 22;
  public static final int EOF = 0;
  public static final int ADD = 20;
  public static final int error = 1;
  public static final int EQ = 21;
}
