//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 26 21:03:14 EST 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class A3Symbol {
  /* terminals */
  public static final int TIMES = 3;
  public static final int READ = 9;
  public static final int SEMICOLON = 17;
  public static final int ELSE = 11;
  public static final int NOTEQ = 21;
  public static final int PLUS = 2;
  public static final int RPAREN = 5;
  public static final int IDENTIFIER = 20;
  public static final int END = 14;
  public static final int RETURN = 12;
  public static final int IF = 10;
  public static final int LPAREN = 4;
  public static final int WRITE = 8;
  public static final int ID = 7;
  public static final int BEGIN = 13;
  public static final int TYPE = 16;
  public static final int QUOTED = 6;
  public static final int COMMA = 18;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int MAIN = 15;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int EQ = 19;
}
